#!/usr/bin/env sh
set -eu
HERE="$(dirname "$(readlink -f "$0")")"
export NODE_ENV=production
export CONFIG_DIRECTORY="${CONFIG_DIRECTORY:-$HOME/.config/seerrng}"
mkdir -p "$CONFIG_DIRECTORY"
exec "$HERE/usr/bin/node" "$HERE/usr/lib/seerrng/dist/index.js" "$@"
